server:
  port: 8090
  servlet:
    context-path: /application

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_BASE:bancodados}
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:${DATABASE_URL}
#    username: ${USER}
#    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/bancodados
    password: postgres
    username: postgres
  liquibase:
    contexts: ${spring.profiles.active}
#    default-schema: //localhost:5432/bancodados
    default-schema: ${DB_BASE:bancodados}
    change-log: classpath:/liquibase/liquibase-changelog.yml
    user: ${DB_LIQUIBASE_USERNAME:${spring.datasource.username}}
    password: ${DB_LIQUIBASE_PASSWORD:${spring.datasource.password}}
    enabled: true